- name: update package
  apt: update_cache=yes

- name: install JDK 11
  apt:
    name: default-jdk
    state: present

- name: add tomcat group
  group:
    name: tomcat

- name: add tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /user/share/tomcat
    createhome: no

- name: create /opt/tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    mode: 0755

- name: download & unarchive
  unarchive:
    src: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.17/bin/apache-tomcat-10.0.17.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]
    mode: 0640
    owner: tomcat
    group: tomcat

- name: Change ownership
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Copy Tomcat service from local to remote
  copy:
    src: /etc/systemd/system/tomcat.service
    dest: /etc/systemd/system/
    mode: 0755   
    owner: tomcat
    group: tomcat  

- name: restart and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    daemon_reload: true  