---
- hosts: localhost
  connection: localhost
  gather_facts: false

  vars_files:
    - variables/variables.yml

  tasks:
    - name: example to create aws security group with ansible
      ec2_group:
        name: creating security group
        description: creating security group
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_access_key: "{{ aws_access_key }}"
        # profile: "{{ profile }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 70.114.65.185/32

          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 70.114.65.185/32  

        tags: 
              Name: main-securitygroup
              Service: elitesolutionIT
              Owner: elitesolutionIT LLC
              Department: devOps engineering
              ManagedWith: ansible
              Environment: dev
              casecode: esc300        